quarkus:
  redis:
    host: redis://localhost:6379
  http:
    limits:
      max-body-size: 10240M
  resteasy:
    gzip:
      enabled: true
      max-input: 10G
  datasource:
    db-kind: mysql
    username: root
    password: my-secret-pw
    jdbc:
      url: jdbc:mysql://127.0.0.1:3306/easy-mooc?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      max-size: 20
      min-size: 10
  hibernate-orm:
    database:
      generation: update
  swagger-ui:
    theme: material

wework:
  login-url: https://work.weixin.qq.com/wwqrlogin/qrcode/%s?login_type=login_admin
  redirect-url: https%3A%2F%2Fwork.weixin.qq.com%2Fwework_admin%2Floginpage_wx%3Fpagekey%3D